config/routes.rb
Rails.application.routes.draw do

  resources :listings do
    resources :orders, only: [ :new, :create ]
  end

  resources :categories

  root 'landings#index'
  get '/about' => 'landings#about'
  get '/contact' => 'landings#contact'
  # get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  # these routes are for showing users a login form, logging them in, and logging them out.
  get     '/login'       =>     'sessions#new'
  post    '/login'       =>     'sessions#create'
  get     '/logout'     =>     'sessions#destroy'

  # these routes will be for signup. The first renders a form in the browse, the second will
  # receive the form and create a user in our database using the data given to us by the user.
  get     '/signup'    =>     'users#new'
  post    '/users'      =>    'users#create'

end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true
  has_many :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	mount_uploader :listing_img, ListingImgUploader
	validates_presence_of :listing_img
	validates :name, :description, :price, presence: true
  	validates :price, numericality: { greater_than: 0 }

  	belongs_to :user
  	belongs_to :category
  	has_many :orders

end

app/models/order.rb
class Order < ActiveRecord::Base

	validates :address, :city, :state, presence: true
	belongs_to :listing
	belongs_to :buyer, class_name: "User"
  	belongs_to :seller, class_name: "User"

end

app/models/user.rb
class User < ActiveRecord::Base

   validates :username, :email, presence: true
   validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
   has_secure_password

   has_many :listings, dependent: :destroy
   has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
   has_many :sales, class_name: "Order", foreign_key: "seller_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    if not current_user
      redirect_to login_path, flash: { danger: "Whoa buddy, that page is off limits. Try logging in first. " }
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authorize, except: [ :show ]
  before_action :find_category, only: [ :edit, :update, :destroy ]

  def index
    @categories = Category.all.order( "created_at DESC" )
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new( category_params )

    if @category.save
      redirect_to categories_path, flash: { info: "New category created successfully" }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update( category_params )
      redirect_to categories_path, flash: { info: "Category successfully updated" }
    else
      render :edit
    end
  end

  def destroy
    @category.destroy

    redirect_to root_path, flash: { info: "Category successfully deleted" }
  end

  private
    def find_category
      @category = Category.find( params[ :id ] )
    end

    def category_params
      params.require( :category ).permit( :name )
    end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController

  def index
    if params[ :category ].blank?
      @listings = Listing.all.order( "created_at DESC" )
    else
      @category_id = Category.find_by( name: params[ :category ] ).id
      @listings = Listing.where( category_id: @category_id ).order( "created_at DESC" )
    end
  end

  def about
  end

  def contact
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :authorize, except: [ :show ]
  before_action :check_user, only: [ :edit, :update, :destroy ]
  before_action :find_listing, only: [ :show, :edit, :update, :destroy, :upvote ]

  def seller
    @listings = Listing.where( user: current_user ).order( "created_at DESC" )
  end

  def index
    # @listings = Listing.all.order( "created_at DESC" )
    @listings = Listing.where( user: current_user ).order( "created_at DESC" )
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def edit
  end

  def create
    @listing = Listing.new( listing_params )
    @listing.user_id = current_user.id

    if current_user.recipient_token.blank?
      Stripe.api_key = ENV[ "stripe_api_key" ]
      token = params[ :stripeToken ]

      recipient = Stripe::Recipient.create(
        # :name => current_user.username,
        :name => "Gareth Bale",
        :type => "individual",
        :bank_account => token
      )

      current_user.recipient_token = recipient.id
      current_user.save
    end

    if @listing.save
      redirect_to @listing, flash: { info: "New listing created successfully" }
    else
      render :new
    end
  end

  def update
    if @listing.update( listing_params )
      redirect_to @listing, flash: { info: "LIsting successfully updated" }
    else
      render :edit
    end
  end

  def destroy
    @listing.destroy

    redirect_to root_path, flash: { info: "Listing successfully deleted" }
  end

  private
    def find_listing
      @listing = Listing.find( params[ :id ] )
    end

    def listing_params
      params.require( :listing ).permit( :name, :description, :price, :quantity, :listing_img, :category_id )
    end

    def check_user
      listing = Listing.find( params[ :id ] )
      if current_user.id != listing.user.id
        redirect_to root_path, flash: { warning: "Sorry, this listing belongs to someone else" }
      end
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authorize, except: [ :show ]
  before_action :find_order, only: [ :show, :edit, :update, :destroy ]

  def sales
    @orders = Order.all.where( seller: current_user ).order( "created_at DESC" )
  end

  def purchases
    @orders = Order.all.where( buyer: current_user ).order( "created_at DESC" )
  end

  def new
    @order = Order.new
    @listing = Listing.find( params[ :listing_id ] )
  end

  def create
    @order = Order.new( order_params )
    @listing = Listing.find( params[ :listing_id ] )
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.seller_id = @seller.id
    @order.buyer_id = current_user.id

    Stripe.api_key = ENV[ "stripe_api_key" ]
    token = params[ :stripeToken ]
    puts "PARAMS STRIPE TOKEN: #{params[:stripeToken]}"

    begin
      charge = Stripe::Charge.create(
        :amount => ( @listing.price * 100 ).floor,
        :currency => "usd",
        :card => token
        )
      flash[ :success ] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[ :danger ] = e.message
    end

    transfer = Stripe::Transfer.create(
      :amount => (@listing.price * 95).floor,
      :currency => "usd",
      :recipient => @seller.recipient_token
    )

    if @order.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def find_listing
      @order = Order.find( params[ :id ] )
    end

    def order_params
      params.require( :order ).permit( :address, :city, :state )
    end

end

# 4000000000000077

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to root_path, flash: { success: "Welcome back #{current_user.username}!" }
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to login_path, flash: { warning: "Hmmm that wasn't right. Try again." }
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { danger: "See ya later alligator!" }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, flash: { success: "Welcome #{current_user.username} your account was successfully created." }
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_categories_table.html.erb
<table class="table table-striped table-bordered table-hover">

    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Action</th>
    </tr>

    <% @categories.each do | category | %>
      <tr>
        <td class="text-center"><%= category.name %></td>
        <td class="text-center">
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Edit", edit_category_path( category ) %></li>
              <li><%= link_to "Destroy", category_path( category ), method: :delete, data: { confirm: "Are you sure?"} %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>

</table>

app/views/categories/_form.html.erb
<%= form_for @category do | f | %>

  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize( @category.errors.count, "error" ) %> prohibited this category from being saved:</h4>
      <ul>
        <% @category.errors.full_messages.each do | msg | %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/categories/edit.html.erb
<br>
<div class="row">
  <div class="col-md-8 .col-sm-8 .col-xs-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-center">Edit Category</h3>
      </div>
      <div class="panel-body">
        <!-- form partial -->
        <%= render 'categories/form' %>
      </div>
    </div>
    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="jumbotron dashboard">
  <h1 class="text-center">Manage Categories</h1>
</div>

<div class="row placeholders">
</div>

<div class="row">
  <div class="col-md-12 .col-sm-12 .col-xs-12">

      <!-- listings table partial -->
      <%= render 'categories/categories_table' %>

  </div>
</div>

<hr>
<%= link_to "New Category", new_category_path, class: "btn btn-primary", data: { no_turbolink: true } %>

app/views/categories/new.html.erb
<br>
<div class="row">
  <div class="col-md-8 .col-sm-8 .col-xs-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-center">Add Category</h3>
      </div>
      <div class="panel-body">
        <!-- form partial -->
        <%= render 'categories/form' %>
      </div>
    </div>
    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/landings/about.html.erb
<h1>This is the about page for All Things Malibu</h1>

app/views/landings/contact.html.erb
<h1>Contact page for All Things Malibu</h1>

app/views/landings/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">Welcome to All Things Malibu</h1>
</div>

<div class="row">

  <% @listings.each do | listing | %>
    <div class="col-sm-3 col-md-3">
      <div class="box panel panel-default">
        <div class="panel-heading panel-img">
          <%= image_tag listing.listing_img, class: "img-responsive index-img" %>
        </div>
        <div class="panel-footer">
          <h3 class="listing-title"><%= "#{ listing.name }" %></h3>
          <p><%= "$#{ listing.price }" %></p>
          <p><%= link_to "View", listing_path( listing ), class: "btn btn-primary" %></p>
          <hr>
          <p>
            Sold by: <%= "#{ listing.user.username }" %>
          </p>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
 <%= content_tag(:div, class: "alert alert-#{name} text-center") do%>
    <%=msg%>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
 <%end%>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-center">I &#x2764; Malibu</p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsed">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">All Things Malibu</a>
    </div>

    <div class="collapse navbar-collapse" id="collapsed">
      <ul class="nav navbar-nav navbar-left">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Browse <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do | category | %>
              <li><%= link_to category.name, root_path( category: category.name ) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- if user is signed in display  there name and logout option -->
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Seller Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Manage Listings", listings_path %></li>
              <li><%= link_to "Sales History", sales_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.username %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Purchase History", purchases_path %></li>
              <li><%= link_to "Sign Out", logout_path %></li>
            </ul>
          </li>
        <!-- if user is not signed in display login and signup -->
        <% else %>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Signup", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>

      </ul>
    </div>
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AllThingsMalibu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <!-- make site responsive for all displays -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV[ "stripe_publishable_key" ] %>
</head>
<body>

  <!-- navbar partial -->
  <%= render 'layouts/navbar' %>

  <div class="container">
    <!-- flash message partial -->
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>

  <!-- footer partial -->
  <%= render 'layouts/footer' %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing do | f | %>

  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>
      <ul>
        <% @listing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>
      JavaScript is not enabled and is required for this form. Enable JavaScript in your web browser settings.
    </noscript>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :listing_img, class: "form-control help-block" %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, placeholder: "$3.87", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.order( :name ), :id, :name, { prompt: "Choose a category" }, { class: "form-control" } %>
  </div>

  <% if current_user.recipient_token.blank? %>
    <h3>Bank Account Information</h3>
    <div class="form-group">
      <%= label_tag :country %>
      <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag :routing_number %>
      <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag :account_number %>
      <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/listings/_listings_table.html.erb
<table class="table table-striped table-bordered table-hover">

    <tr>
      <th class="text-center">Image</th>
      <th class="text-center">Name</th>
      <th class="text-center">Description</th>
      <th class="text-center">Price</th>
      <th class="text-center">Action</th>
    </tr>

    <% @listings.each do | listing | %>
      <tr>
        <td class="text-center"><%= image_tag listing.listing_img, class: "img-responsive table-img" %></td>
        <td class="text-center"><%= listing.name %></td>
        <td class="text-center"><%= listing.description %></td>
        <td class="text-center"><%= number_to_currency( listing.price ) %></td>
        <td class="text-center">
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Show", listing_path( listing ) %></li>
              <li><%= link_to "Edit", edit_listing_path( listing ) %></li>
              <li><%= link_to "Destroy", listing_path( listing ), method: :delete, data: { confirm: "Are you sure?"} %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>

</table>

app/views/listings/edit.html.erb
<br>
<div class="row">
  <div class="col-md-8 .col-sm-8 .col-xs-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-center">Edit Listing</h3>
      </div>
      <div class="panel-body">
        <!-- form partial -->
        <%= render 'listings/form' %>
      </div>
    </div>
    <%= link_to 'Back', listings_path %>
  </div>
</div>

app/views/listings/index.html.erb
<div class="jumbotron dashboard">
  <h1 class="text-center">Manage Listings</h1>
</div>

<div class="row placeholders">
</div>

<div class="row">
  <div class="col-md-12 .col-sm-12 .col-xs-12">

      <!-- listings table partial -->
      <%= render 'listings/listings_table' %>

  </div>
</div>

<hr>
<%= link_to "New LIsting", new_listing_path, class: "btn btn-primary", data: { no_turbolink: true } %>

app/views/listings/new.html.erb
<br>
<div class="row">
  <div class="col-md-8 .col-sm-8 .col-xs-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-center">Add Listing</h3>
      </div>
      <div class="panel-body">
        <!-- form partial -->
        <%= render 'listings/form' %>
      </div>
    </div>
    <%= link_to 'Back', listings_path %>
  </div>
</div>

app/views/listings/seller.html.erb
<div class="jumbotron dashboard">
  <h1 class="text-center">Seller</h1>
</div>

<div class="row placeholders">
</div>

<hr>

<div class="row">
  <div class="col-md-12 .col-sm-12 .col-xs-12">
    <div class="table-responsive">
      <!-- listings table partial -->
      <%= render 'listings/listings_table' %>
    </div>
  </div>
</div>

<hr>
<%= link_to "Add LIsting", new_listing_path, class: "btn btn-primary" %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-4 .col-sm-4 .col-xs-4 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading panel-img">
        <%= image_tag @listing.listing_img, class: "img-responsive show-img" %>
      </div>
      <div class="panel-footer">
        <h3><%= "#{ @listing.name }" %></h3>
        <p><%= "#{ @listing.description }" %></p>
        <p><%= "$#{ @listing.price }" %></p>
        <p><%= "#{ @listing.category.name }" %></p>
        <p><%= link_to "Buy It Now", new_listing_order_path( @listing ), class: "btn btn-primary", data: { no_turbolink: true } %></p>
        <hr>
        <p>
          Sold by: <%= "#{ @listing.user.username }" %>
        </p>
        <% if current_user == @listing.user.id %>
          <%= link_to "Edit", edit_listing_path( @listing ), class: "btn btn-warning" %></td>
          <%= link_to "Destroy", listing_path( @listing ), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?"} %></td>
        <% end %>
      </div>
    </div>
    <%= link_to 'Back', listings_path  %>
  </div>
</div>


<!-- #{time_ago_in_words( @listing.created_at ) } ago -->

app/views/orders/_form.html.erb
<%= form_for( [ @listing, @order ] ) do | f | %>

  <% if @order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize( @order.errors.count, "error" ) %> prohibited this listing from being saved:</h4>
      <ul>
        <% @error.errors.full_messages.each do | msg | %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>
      JavaScript is not enabled and is required for this form. Enable JavaScript in your web browser settings.
    </noscript>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, placeholder: "Address", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, placeholder: "State", class: "form-control" %>
  </div>
  <!-- *********************************Stripe******************************* -->
  <div class="form-group">
    <div class="row">
      <div class="col-md-8">
        <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
      </div>
      <div class="col-md-4">
        <%= label_tag :card_code, "CVC" %>
        <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag nil, "Expiration Date" %>
    <div class="row">
      <div class="col-md-3">
        <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
      </div>
      <div class="col-md-3">
        <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
      </div>
    </div>
  </div>
  <!-- *********************************End Stripe******************************* -->
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/orders/_purchases_table.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="text-center">Image</th>
    <th class="text-center">Item</th>
    <th class="text-center">Price</th>
    <th class="text-center">Seller</th>
    <th class="text-center">Date Purchased</th>
  </tr>

  <% @orders.each do | order | %>
    <tr>
      <td class="text-center"><%= image_tag order.listing.listing_img, class: "img-responsive table-img" %></td>
      <td class="text-center"><%= order.listing.name %></td>
      <td class="text-center"><%= number_to_currency( order.listing.price ) %></td>
      <td class="text-center"><%= order.seller.username %></td>
      <td class="text-center"><%= order.created_at.strftime( "%B %-d, %Y" ) %></td>
    </tr>
  <% end %>
</table>

app/views/orders/_sales_table.html.erb
<table class="table table-striped table-bordered table-hover">
  <tr>
    <th class="text-center">Image</th>
    <th class="text-center">Item</th>
    <th class="text-center">Price</th>
    <th class="text-center">Customer</th>
    <th class="text-center">Date Sold</th>
  </tr>

  <% @orders.each do | order | %>
    <tr>
      <td class="text-center"><%= image_tag order.listing.listing_img, class: "img-responsive table-img" %></td>
      <td class="text-center"><%= order.listing.name %></td>
      <td class="text-center"><%= number_to_currency( order.listing.price ) %></td>
      <td class="text-center"><%= order.buyer.username %></td>
      <td class="text-center"><%= order.created_at.strftime( "%B %-d, %Y" ) %></td>
    </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<br>
<div class="row">
  <div class="col-md-12 .col-sm-12 .col-xs-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="text-center">Order</h3>
      </div>
      <div class="panel-body">
        <div class="col-md-4">

            <%= image_tag @listing.listing_img, class: "img-responsive show-img" %>

          <h3><%= @listing.name %></h3>
          <h4><%= number_to_currency(@listing.price) %></h4>
        </div>
        <div class="col-md-8">
          <!-- form partial -->
          <%= render 'orders/form' %>
        </div>
      </div>
    </div>
    <%= link_to 'Back', listing_path( @listing ) %>
  </div>
</div>

app/views/orders/purchases.html.erb
<div class="jumbotron dashboard">
  <h1 class="text-center">Purchase History</h1>
</div>

<div class="row placeholders">
</div>

<hr>

<div class="row">
  <div class="col-md-12 .col-sm-12 .col-xs-12">
    <div class="table-responsive">
      <!-- listings table partial -->
      <%= render 'orders/purchases_table' %>
    </div>
  </div>
</div>

<hr>
<%= link_to "Add LIsting", new_listing_path, class: "btn btn-primary" %>

app/views/orders/sales.html.erb
<div class="jumbotron dashboard">
  <h1 class="text-center">Sales History</h1>
</div>

<div class="row placeholders">
</div>

<hr>

<div class="row">
  <div class="col-md-12 .col-sm-12 .col-xs-12">
    <div class="table-responsive">
      <!-- listings table partial -->
      <%= render 'orders/sales_table' %>
    </div>
  </div>
</div>

<hr>
<%= link_to "Add LIsting", new_listing_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<!-- session form partial -->
<%= render 'users/form' %>